const InvestmentList = [
	{
		title: `109-111 West 24th Street`,
		description: `On behalf of ownership, HKS Real Estate Advisors is pleased to present for sale, Chelsea office property. Ideally located a block away from Madison Square Park and the Flatiron District, and also a few steps away from the 1, B, D, F, M trains, plus the PATH. The area is known for its plentiful culinary and shopping amenities and some of the city's most walkable streets. The property has seven stories and six are for office use, plus one on the ground floor for retail.`,
		photo: `/assets/listings/111-West-24th-Street.jpg`,
		h1: `±46,299 SQ.FT.`,
		l1: `RBA`,
		h2: `50'`,
		l2: `Frontage`,
		h3: `7`,
		l3: `# of Stories`,
		web: `https://111w24.com`,
	},
	{
		title: `Rare Development Opportunity / 354 West 52nd Street`,
		description: `On behalf of ownership, HKS Real Estate Advisors is pleased to present, 354 West 52nd Street for sale. The block-through lot is ideally located on 52nd Street between 8th and 9th avenues in the Clinton-Midtown West neighborhood of Manhattan. The development site is currently operated as a parking lot and measures approximately 9,540 square feet. The residential and community facility FAR is 4.20 providing for a potential floor area of 40,068 square feet. The site has 75 feet of frontage on 52nd Street and 20 feet of frontage on 51st Street.`,
		photo: `/assets/listings/354-West-52nd-Street.jpg`,
		h1: `40,068 SQ.FT.`,
		l1: `Max Floor Area`,
		h2: `75' X 201' (IRR.)`,
		l2: `Lot Dimensions`,
		h3: `R8/CL`,
		l3: `Zoning/Special District`,
		flyer: `/assets/listings/354-West-52nd-Street_flyer.pdf`,
	},
	{
		title: `Astoria Value-Add: 34-55 32nd Street`,
		description: `4-Story Opportunity Zone asset with 7 free-market units and 1 restaurant.  All seven apartments are 2 bedroom-2 baths, attracting middle-class young professionals and families.  This corner lot retail space is home to New York's only Welsh restaurant and bar.`,
		photo: `/assets/listings/34-55-32nd-Street.jpg`,
		h1: `8`,
		l1: `Total Units`,
		h2: `±6,480 Sq.Ft.`,
		l2: `Building Size`,
		h3: `$240,396`,
		l3: `Gross Income`,
		flyer: `/assets/listings/34-55-32nd-Street-flyer.pdf`,
	},
	{
		title: `Industrial Opportunity Zone, South Bronx`,
		description: `Portfolio of commercial/industrial properties in the South Bronx with proximity to 4, 5, 6 Subway lines as well as the Robert F. Kennedy, 145th Street, Madison Avenue, Third Avenue, and Willis Avenue Bridges.  The properties total ± 100,000 square feet with an additional 21,000 square feet of unused development rights or 167,000 square feet of unused development rights with community facility bonus.`,
		photo: `/assets/listings/industrial-opportunity-zone.jpg`,
		h1: `±100,000 SQ.FT.`,
		l1: `Building Size`,
		h2: `±55,784 SQ.FT.`,
		l2: `Lot Size`,
		h3: `± 21,040 SQ.FT.`,
		l3: `Unused Development Rights`,
		flyer: ``,
	},
	{
		title: `LIC Opportunity Zone, Ground-Lease or JV Development`,
		description: `Block-thru lot with over 330,000 square feet of development rights.  This Qualified Opportunity Zone lot is ripe for taking advantage of the Federal tax benefits provided in exchange for improving the lot and opening new businesses.  Zoning permits for construction of Industrial, Office, and Retail.`,
		photo: `/assets/listings/lic-opportunity-zone.jpg`,
		h1: `51,411`,
		l1: `Lot Sq.Ft.`,
		h2: `334,172`,
		l2: `Buildable Sq.Ft.`,
		h3: `M1-5`,
		l3: `Zoning`,
		flyer: ``,
	},
];

export default InvestmentList;
