const NewsList = [
	{
		image: `/assets/transaction-placeholder.jpg`,
		link: `https://nyrej.com/2020-ones-to-watch-max-ralby-hks-real-estate-advisors-llc`,
		title: `2020 Ones to Watch: Max Ralby, HKS Real Estate Advisors LLC`,
		date: `August 18, 2020`,
		publisher: `NYREJ`,
		publisherLink: `https://nyrej.com`,
		text: `The closing of a $24 million construction loan in the Bronx for the new headquarters for Samaritan Day Top Village. I tracked this project for over a year, so landing the assignment and securing the financing on it was a big stepping stone so early in my career.`,
	},
	{
		image: `/assets/transaction-placeholder.jpg`,
		link: `https://nyrej.com/carillo-of-hks-real-estate-advisors-and-tapper-of-lee-nyc-negotiate-99-year-leasehold`,
		title: `Carillo of HKS Real Estate Advisors and Tapper of Lee NYC negotiate 99-year leasehold`,
		date: `November 19, 2019`,
		publisher: `NYREJ`,
		publisherLink: `https://nyrej.com`,
		text: `Manhattan, NY Peter Carillo, principal/senior managing director of HKS Real Estate Advisors and Ben Tapper, senior managing director of Lee & Associates NYC (LeeNYC), have negotiated a 99-year leasehold at 777 Eighth Ave., between West 47th and West 48th Sts.`,
	},
	{
		image: `/assets/transaction-placeholder.jpg`,
		link: `https://rew-online.com/peter-carillo-to-launch-new-sales-division-at-hks-capital/`,
		title: `Peter Carillo to launch new sales division at HKS Capital`,
		date: `September 26, 2018`,
		publisher: `Real Estate Weekly`,
		publisherLink: `https://rew-online.com`,
		text: `Another Eastern Consolidate alumnus has been tapped to build out an investment sales platform for a New York company. Peter Carillo, a record-breaking producer at the now shuttered firm, will head a new division at financial advisory HKS Partners.`,
	},
	{
		image: `/assets/transaction-placeholder.jpg`,
		link: `http://rew-online.com/2018/04/15/53034/`,
		title: `2018's Rising Stars of Real Estate`,
		date: `August 18, 2020`,
		publisher: `Real Estate Weekly`,
		publisherLink: `http://rew-online.com/`,
		text: `Michael Lee, 28, is a rising star at financial advisory firm HKS Capital Partners where he has been part of the team since the company was founded in 2011. In 2015 he was appointed a partner at HKS Capital Partners where he has originated loans alongside commercial`,
	},
	{
		image: `/assets/transaction-placeholder.jpg`,
		link: `https://nyrej.com/2020-ones-to-watch-max-ralby-hks-real-estate-advisors-llc`,
		title: 'Sizing up NYC`s debt brokerage powerhouses',
		date: `May 3, 2018`,
		publisher: `NYREJ`,
		publisherLink: `https://nyrej.com`,
		text: `UPDATED, May 3, 12:42 p.m.: HNA Group's $2.21 billion purchase of 245 Park Avenue — the city's biggest investment sales deal of 2017 — was brokered by the world's largest property services firm, CBRE.`,
	},
	{
		image: `/assets/transaction-placeholder.jpg`,
		link: `https://www.mannpublications.com/mannreport/2018/05/01/commercial-corner-charles-yellen/`,
		title: `Commercial Corner: Charles Yellen`,
		date: `May 1, 2018`,
		publisher: `Mann Report`,
		publisherLink: `https://www.mannpublications.com/`,
		text: `Charles Yellen joined New York-based capital advisory firm HKS Capital Partners at the start of 2017 as its new managing director where he manages the firm's growing practice and works in collaboration with the founding partners and staff to mentor HKS brokers and trainees.`,
	},
];

export default NewsList;
