const teamMembers = [
	{
		name: 'Ayush Kapahi',
		title: 'Principal and Founding Partner',
		phone: '(212) 254-1600',
		email: 'akapahi@hks.com',
		photo: '/assets/team/akapahi.jpg',
	},
	{
		name: 'John Harrington',
		title: 'Principal and Founding Partner',
		phone: '(212) 254-1600',
		email: 'jharrington@hks.com',
		photo: '/assets/team/jharrington.jpg',
	},
	{
		name: 'Jerry Swartz',
		title: 'Principal and Founding Partner',
		phone: '(212) 254-1600',
		email: 'jswartz@hks.com',
		photo: '/assets/team/jswartz.jpg',
	},
	{
		name: 'Michael Lee',
		title: 'Principal and Partner',
		phone: '(212) 254-1600 x 101',
		email: 'mlee@hks.com',
		photo: '/assets/team/mlee.jpg',
	},
	{
		name: 'Peter Carillo',
		title: 'Principal, Senior Managing Director',
		phone: '(212) 254-1600 x 118',
		email: 'pcarillo@hks.com',
		photo: '/assets/team/pcarillo.jpg',
	},
	{
		name: 'Charles Yellen',
		title: 'Senior Managing Director',
		phone: '(212) 254-1600',
		email: 'cyellen@hks.com',
		photo: '/assets/team/cyellen.jpg',
	},
	{
		name: 'Max Ralby',
		title: 'Managing Director',
		phone: '(212) 254-1600',
		email: 'mralby@hks.com',
		photo: '/assets/team/mralby.jpg',
	},
	{
		name: 'Eugene Weinraub',
		title: 'Managing Director',
		phone: '(212) 254-1600',
		email: 'eweinraub@hks.com',
		photo: '/assets/team/eweinraub.jpg',
	},
	{
		name: 'Jay Stern-Szczepaniak',
		title: 'Associate Director',
		phone: '(212) 254-1600',
		email: 'jstern@hks.com',
		photo: '/assets/team/jstern.jpg',
	},
	{
		name: 'Daniel Kowalsky',
		title: 'Director of Financial Services',
		phone: '(212) 254-1600',
		email: 'dkowalsky@hks.com',
		photo: '/assets/team/dkowalsky.jpg',
	},
	{
		name: 'Arthur Safdeye',
		title: 'Analyst',
		phone: '(212) 254-1600',
		email: 'asafdeye@hks.com',
		photo: '/assets/team/asafdeye.jpg',
	},
	{
		name: 'James Stavrakis',
		title: 'Analyst',
		phone: '(212) 254-1600 x110',
		email: 'jstavrakis@hks.com',
		photo: '/assets/team/jstavrakis.jpg',
	},
	{
		name: 'Dean Katz',
		title: 'Analyst',
		phone: '(212) 254-1600',
		email: 'dkatz@hks.com',
		photo: '/assets/team/dkatz.jpg',
	},
	{
		name: 'Alex Dobosh',
		title: 'Principal and Partner',
		phone: '(212) 254-1600',
		email: 'adobosh@hks.com',
		photo: '/assets/team/adobosh.jpg',
	},
	{
		name: 'Antonio Lulli',
		title: 'Real Estate Financial Analyst',
		phone: '(212) 254-1600 x 112',
		email: 'alulli@hks.com',
		photo: '/assets/team/alulli.png',
	},
	{
		name: 'Jeremy Pentek',
		title: 'Underwriting Analyst',
		phone: '(212) 254-1600',
		email: 'jpentek@hks.com',
		photo: '/assets/team/jpentek.jpg',
	},
];

export default teamMembers;
