const TransactionsList = [
	{
		category: 'Investment Sales',
		address: '305 West 48th Street & 777 8th Avenue',
		neighbourhood: 'Times Square',
		borough: 'Manhattan',
		type: 'Development Site',
		image: '/assets/transactions/is/is1.jpg',
		price: '$909,000,000',
	},
	{
		category: 'Investment Sales',
		address: '500 Fifth Avenue',
		neighbourhood: 'Plaza District',
		borough: 'Manhattan',
		type: 'Office',
		image: '/assets/transactions/is/is2.jpg',
		price: '$22,480,000',
	},
	{
		category: 'Investment Sales',
		address: 'East Harlem Portfolio',
		neighbourhood: 'East Harlem',
		borough: 'Upper Manhattan',
		type: 'Multifamily',
		image: '/assets/transactions/is/is3.jpg',
		price: '$225,000,000',
	},
	{
		category: 'Investment Sales',
		address: '120 East Street Road',
		neighbourhood: 'Philadelphia Suburbs',
		borough: 'Warminister, PA',
		type: 'Multifamily',
		image: '/assets/transactions/is/is4.jpg',
		price: '$21,000,000',
	},
	{
		category: 'Investment Sales',
		address: '5 East 51st Street',
		neighbourhood: 'Midtown East',
		borough: 'Manhattan',
		type: 'Assemblage',
		image: '/assets/transactions/is/is5.jpg',
		price: '$12,600,000',
	},
	{
		category: 'Investment Sales',
		address: '12391 West Sunrise Boulevard',
		neighbourhood: 'South Florida',
		borough: 'Plantation, FL',
		type: 'Retail',
		image: '/assets/transactions/is/is6.jpg',
		price: '$8,100,000',
	},
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: 'Investment Sales Ends Here',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	{
		category: 'Capital Advisory',
		address: 'High-Rise Apartment Building in Manhattan',
		type: 'Refinance',
		image: '/assets/transactions/ca/ca1.jpg',
		price: '$75,000,000',
	},
	{
		category: 'Capital Advisory',
		address: 'Long Island City Luxury Construction',
		type: 'Construction Loan, Ground-Up',
		image: '/assets/transactions/ca/ca2.jpg',
		price: '$150,000,000',
	},
	{
		category: 'Capital Advisory',
		address: 'The Sagamore Hotel, South Beach',
		type: 'Acquisition + Renovation',
		image: '/assets/transactions/ca/ca3.jpg',
		price: '$45,000,000',
	},
	{
		category: 'Capital Advisory',
		address: 'Mixed-Use Asset & Multifamily Building in Manhattan',
		type: 'Cash-out Refinance',
		image: '/assets/transactions/ca/ca4.jpg',
		price: '$20,800,000',
	},
	{
		category: 'Capital Advisory',
		address: 'Chinatown Office and Retail Portfolio',
		type: 'Refinance',
		image: '/assets/transactions/ca/ca5.jpg',
		price: '$19,000,000',
	},
	{
		category: 'Capital Advisory',
		address: 'Brooklyn College Student Housing',
		type: 'FNMA Floating Rate',
		image: '/assets/transactions/ca/ca6.jpg',
		price: '$32,000,000',
	},
	// {
	// 	category: 'Capital Advisory',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Capital Advisory',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Capital Advisory',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Capital Advisory',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Capital Advisory',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Capital Advisory',
	// 	address: 'Captial Advisory Ends Here',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: '/assets/transaction-placeholder.jpg',
	// },
];

export default TransactionsList;
