const TransactionsList = [
	{
		category: 'Investment Sales',
		address: '305 West 48th Street & 777 8th Avenue',
		neighbourhood: 'Times Square',
		borough: 'Manhattan',
		type: 'Development Site',
		image: 'assets/transaction-placeholder.jpg',
	},
	{
		category: 'Investment Sales',
		address: '500 Fifth Avenue',
		neighbourhood: 'Plaza District',
		borough: 'Manhattan',
		type: 'Office',
		image: 'assets/transaction-placeholder.jpg',
	},
	{
		category: 'Investment Sales',
		address: 'East Harlem Portfolio',
		neighbourhood: 'East Harlem',
		borough: 'Upper Manhattan',
		type: 'Multifamily',
		image: 'assets/transaction-placeholder.jpg',
	},
	{
		category: 'Investment Sales',
		address: '120 East Street Road',
		neighbourhood: 'Philadelphia Suburbs',
		borough: 'Warminister, PA',
		type: 'Multifamily',
		image: 'assets/transaction-placeholder.jpg',
	},
	{
		category: 'Investment Sales',
		address: '5 East 51st Street',
		neighbourhood: 'Midtown East',
		borough: 'Manhattan',
		type: 'Assemblage',
		image: 'assets/transaction-placeholder.jpg',
	},
	{
		category: 'Investment Sales',
		address: '12391 West Sunrise Boulevard',
		neighbourhood: 'South Florida',
		borough: 'Plantation, FL',
		type: 'Retail',
		image: 'assets/transaction-placeholder.jpg',
	},
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Investment Sales',
	// 	address: 'Investment Sales Ends Here',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	{
		category: 'Capital Advisory',
		address: 'High-Rise Apartment Building in Manhattan',
		type: 'Refinance',
		image: 'assets/transaction-placeholder.jpg',
	},
	{
		category: 'Capital Advisory',
		address: 'Long Island City Luxury Construction',
		type: 'Construction Loan, Ground-Up',
		image: 'assets/transaction-placeholder.jpg',
	},
	{
		category: 'Capital Advisory',
		address: 'The Sagamore Hotel, South Beach',
		type: 'Aquisition + Renovation',
		image: 'assets/transaction-placeholder.jpg',
	},
	{
		category: 'Capital Advisory',
		address: 'Mixed-Use Asset & Multifamily Building in Manhattan',
		type: 'Cash-out Refinance',
		image: 'assets/transaction-placeholder.jpg',
	},
	{
		category: 'Capital Advisory',
		address: 'Chinatown Office and Retail Portfolio',
		type: 'Refinance',
		image: 'assets/transaction-placeholder.jpg',
	},
	{
		category: 'Capital Advisory',
		address: 'Brooklyn College Student Housing',
		type: 'FNMA Floating Rate',
		image: 'assets/transaction-placeholder.jpg',
	},
	// {
	// 	category: 'Capital Advisory',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Capital Advisory',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Capital Advisory',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Capital Advisory',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Capital Advisory',
	// 	address: '84 Bowery',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
	// {
	// 	category: 'Capital Advisory',
	// 	address: 'Captial Advisory Ends Here',
	// 	neighbourhood: 'Bowery',
	// 	borough: 'Manhattan',
	// 	type: 'Medical Office',
	// 	image: 'assets/transaction-placeholder.jpg',
	// },
];

export default TransactionsList;
